#!/bin/sh
# Proves the contributor policy rejects what it claims to reject and accepts a normal commit.
# Run: sh scripts/tests/policy-test.sh      Exit code 0 means every case behaved as expected.
root=$(cd "$(dirname "$0")/../.." && pwd)
pass=0
failed=0

ok() { # description, command...  (must succeed)
    d=$1; shift
    if "$@" >/dev/null 2>&1; then pass=$((pass + 1)); else failed=$((failed + 1)); echo "FAIL (expected accept): $d"; fi
}
no() { # description, command...  (must fail)
    d=$1; shift
    if "$@" >/dev/null 2>&1; then failed=$((failed + 1)); echo "FAIL (expected reject): $d"; else pass=$((pass + 1)); fi
}

# ---- rules --------------------------------------------------------------------------------------
. "$root/scripts/lib/policy.sh"

ok "plain subject"            subject_ok "feat(auth): add google sign-in button"
ok "no scope"                 subject_ok "fix: handle a null user"
ok "merge commit"             subject_ok "Merge branch 'main' into feat/1-x"
no "no type"                  subject_ok "Add stuff"
no "capital after colon"      subject_ok "feat(auth): Add button"
no "trailing period"          subject_ok "feat: adds button."
no "unknown type"             subject_ok "feature: add button"
no "too long"                 subject_ok "feat: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

ok "branch"                   branch_ok "feat/12-google-sign-in"
no "branch wrong type"        branch_ok "feature/12-google"
no "branch without issue"     branch_ok "feat/google-sign-in"
no "branch underscore"        branch_ok "feat/12_google"
no "branch upper case"        branch_ok "Feat/12-google"
no "main is not a work branch" branch_ok "main"
ok "GitHub revert branch"     branch_ok "revert-12-feat/12-google-sign-in"

no "claude trailer"           check_message "feat: x

Co-Authored-By: Claude <noreply@anthropic.com>"
no "any co-author"            check_message "feat: x

Co-authored-by: Someone <someone@example.com>"
no "generated with footer"    check_message "feat: x

Generated with [Claude Code](https://claude.com/claude-code)"
no "robot emoji"              check_message "feat: x

🤖 made by a tool"
no "made with footer"         check_message "feat: x

Made with Gemini in Antigravity"
no "created using footer"     check_message "feat: x

Created using OpenAI Codex"
ok "cursor is an Android word" check_message "fix(offline): close the Cursor after each query"
ok "naming a tool is not a byline" check_message "docs(agents): explain the claude code settings"
ok "generated by a non-AI tool" check_message "chore(build): remove files generated by android studio"
ok "ordinary body"            check_message "feat(auth): add google sign-in button

Adds the button and the Firebase credential exchange.
Closes #12"

no "identity Claude"          check_identity "Claude" "noreply@anthropic.com" author
no "identity Gemini"          check_identity "Gemini CLI" "gemini@example.com" author
no "identity copilot bot"     check_identity "github-copilot[bot]" "1+Copilot@users.noreply.github.com" author
no "identity Antigravity"     check_identity "Antigravity Agent" "a@example.com" author
ok "identity human"           check_identity "Tran Duc Phat" "tranducphat1836@gmail.com" author
ok "identity human vietnamese" check_identity "Nguyễn Thúy Ngân" "ngan@example.com" author

# ---- server side functions ----------------------------------------------------------------------
export POLICY_SOURCE_ONLY=1 POLICY_SCRIPTS_DIR="$root/scripts"
. "$root/scripts/ci-policy.sh"
set +e
set +u
b64() { printf '%s' "$1" | base64 | tr -d '\n'; }
count_problems() { problems=0; "$@" >/dev/null 2>&1; echo "$problems"; }

# expect <description> <none|some> <command...>: none means the check reports no problem, some means it reports one.
expect() {
    d=$1; want=$2; shift 2
    got=$(count_problems "$@")
    case "$want:$got" in
        none:0) pass=$((pass + 1)) ;;
        none:*) failed=$((failed + 1)); echo "FAIL (expected accept): $d" ;;
        some:0) failed=$((failed + 1)); echo "FAIL (expected reject): $d" ;;
        *) pass=$((pass + 1)) ;;
    esac
}

good=$(b64 "feat(auth): add google sign-in button")
expect "team member commit"            none check_commit_row aaaaaaaa1 tahpnart8 tahpnart8 "Tran Duc Phat" a@b.c "$good"
expect "login case and web-flow"       none check_commit_row aaaaaaaa1 TAHPNART8 web-flow "Tran Duc Phat" a@b.c "$good"
expect "unlinked e-mail"               some check_commit_row aaaaaaaa2 NONE NONE "Someone" a@b.c "$good"
expect "outsider"                      some check_commit_row aaaaaaaa3 stranger stranger "Stranger" a@b.c "$good"
expect "AI identity"                   some check_commit_row aaaaaaaa4 tahpnart8 tahpnart8 "Claude" noreply@anthropic.com "$good"
expect "outside co-author"             some check_commit_row aaaaaaaa5 tahpnart8 tahpnart8 "Tran Duc Phat" a@b.c "$(b64 "feat: x

Co-authored-by: Gemini <g@example.com>")"
expect "team suggestion co-author"     none check_commit_row aaaaaaaa6 PmSubin PmSubin "Nguyen Hoang Phuc" a@b.c "$(b64 "fix(ui): apply review suggestion

Co-authored-by: Tran Duc Phat <123456+tahpnart8@users.noreply.github.com>")"
expect "outsider noreply co-author"    some check_commit_row aaaaaaaa7 PmSubin PmSubin "Nguyen Hoang Phuc" a@b.c "$(b64 "fix(ui): apply review suggestion

Co-authored-by: Someone <99+stranger@users.noreply.github.com>")"
expect "claude noreply co-author"      some check_commit_row aaaaaaaa8 PmSubin PmSubin "Nguyen Hoang Phuc" a@b.c "$(b64 "fix(ui): x

Co-authored-by: Claude <noreply@anthropic.com>")"

T="feat(listing): add x"
expect "decisions rewrite"             some check_files_row memory/decisions.md modified 3 - "$T" ""
expect "decisions append"              none check_files_row memory/decisions.md modified 0 - "$T" ""
expect "delete app file, no issue"     some check_files_row PUBGApp/app/src/main/java/x/Y.java removed 40 - "$T" "Closes #1"
expect "rename app file, no issue"     some check_files_row PUBGApp/app/src/main/java/x/Z.java renamed 0 PUBGApp/app/src/main/java/x/Y.java "$T" "Closes #1"
expect "plain edit"                    none check_files_row PUBGApp/app/src/main/java/x/Y.java modified 40 - "$T" "Closes #1"
expect "large deletion only warns"     none check_files_row PUBGApp/app/src/main/java/x/Y.java modified 300 - "$T" "Closes #1"
expect "dependency in a feature PR"    some check_files_row PUBGApp/gradle/libs.versions.toml modified 1 - "$T" ""
expect "app gradle in a feature PR"    some check_files_row PUBGApp/app/build.gradle.kts modified 1 - "$T" ""
expect "dependency in a build PR"      none check_files_row PUBGApp/gradle/libs.versions.toml modified 1 - "build(firebase): add firebase bom" ""
expect "dependency in a chore PR"      none check_files_row PUBGApp/app/build.gradle.kts modified 1 - "chore(deps): add room" ""

# Pull request body: the template's own hints live in <!-- --> comments and must not count.
tmpl=$(cat "$root/.github/PULL_REQUEST_TEMPLATE.md")
if body_links_issue "$(strip_comments "$tmpl")"; then failed=$((failed + 1)); echo "FAIL: unfilled template satisfied the Closes check"; else pass=$((pass + 1)); fi
if body_links_issue "$(strip_comments "$(printf '%s\n' "$tmpl" | sed 's/^Closes #$/Closes #12/')")"; then pass=$((pass + 1)); else failed=$((failed + 1)); echo "FAIL: filled template rejected"; fi
if body_links_issue "$(strip_comments "Closes: none")"; then pass=$((pass + 1)); else failed=$((failed + 1)); echo "FAIL: Closes: none rejected"; fi
if body_links_issue "$(strip_comments "Reverts tahpnart8/NHOM3-MobileApp#12")"; then pass=$((pass + 1)); else failed=$((failed + 1)); echo "FAIL: GitHub revert body rejected"; fi
case "$(strip_comments "a <!-- x
Closes #9
--> b")" in *"Closes"*) failed=$((failed + 1)); echo "FAIL: multi-line comment not stripped" ;; *) pass=$((pass + 1)) ;; esac
set -u

# ---- hooks in a throwaway repository ------------------------------------------------------------
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
git init -q "$tmp/repo"
cd "$tmp/repo"
git config user.name "Tran Duc Phat"
git config user.email "human@example.com"
git config core.hooksPath "$root/.githooks"
git config commit.gpgsign false
mkdir memory
printf '# Decisions\n\n## 2026-09-25 - First\n' >memory/decisions.md
git add memory/decisions.md

ok "clean commit passes the hooks"    git commit -q -m "chore(docs): add the decision ledger"
git commit -q --allow-empty -m "feat: x

Co-Authored-By: Claude <noreply@anthropic.com>" >/dev/null 2>&1 && { failed=$((failed + 1)); echo "FAIL: hook accepted a Claude trailer"; } || pass=$((pass + 1))
git commit -q --allow-empty -m "Add stuff" >/dev/null 2>&1 && { failed=$((failed + 1)); echo "FAIL: hook accepted a bad subject"; } || pass=$((pass + 1))
GIT_AUTHOR_NAME="Gemini" GIT_AUTHOR_EMAIL="g@example.com" git commit -q --allow-empty -m "feat: x" >/dev/null 2>&1 && { failed=$((failed + 1)); echo "FAIL: hook accepted an AI author"; } || pass=$((pass + 1))

printf 'x\n' >local.properties
git add local.properties
git commit -q -m "chore: add local properties" >/dev/null 2>&1 && { failed=$((failed + 1)); echo "FAIL: pre-commit accepted local.properties"; } || pass=$((pass + 1))
git reset -q
rm -f local.properties

printf '# Decisions\n\n## 2026-09-25 - Rewritten\n' >memory/decisions.md
git add memory/decisions.md
no "rewriting the ledger is refused" sh "$root/scripts/check-decisions.sh"
printf '# Decisions\n\n## 2026-09-25 - First\n\n## 2026-09-26 - Second\n' >memory/decisions.md
git add memory/decisions.md
ok "appending to the ledger is allowed" sh "$root/scripts/check-decisions.sh"
git reset -q --hard

sha=$(git rev-parse HEAD)
no "push to main is refused"      sh -c "printf 'refs/heads/main $sha refs/heads/main 0000000000000000000000000000000000000000\n' | sh '$root/.githooks/pre-push' origin url"
no "bad branch name is refused"   sh -c "printf 'refs/heads/mywork $sha refs/heads/mywork 0000000000000000000000000000000000000000\n' | sh '$root/.githooks/pre-push' origin url"
ok "good branch name is allowed"  sh -c "printf 'refs/heads/feat/1-x $sha refs/heads/feat/1-x 0000000000000000000000000000000000000000\n' | sh '$root/.githooks/pre-push' origin url"

echo "policy tests: $pass passed, $failed failed"
[ "$failed" -eq 0 ]
